name: RocketStore
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  provider: ^6.0.1
  fluttertoast: ^8.2.2
  image_picker: ^0.8.4+2
  cloudinary_public: ^0.21.0
  cupertino_icons: ^1.0.2
  location: ^5.0.0
  path_provider: ^2.1.1
  geocoding: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-SemiBold.ttf
  assets:
    - assets/icon/icon.png

  

